services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile  # Dockerfile のパスを明示的に指定
    ports:
      - "3000:3000"
      - "5555:5555"  # Prisma Studio 用 ←これ追加
    volumes:
      - "/app/node_modules" # ←追加
      - .:/app
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
  mysql:
    # MySQL コンテナに使用するイメージを指定
    image: mysql:8.0
    # コンテナ内で使用される環境変数を定義
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      # 名前付きボリュームを MySQL コンテナに紐づける
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
      # - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  # 名前付きボリュームの作成
  mysqldata: